language: node_js
services: rethinkdb
sudo: required
node_js:
  - "0.11"
  - "0.10"
  - "4"
  - "5"
script: make test-once
before_script:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install rethinkdb
  - sleep 15
  - rethinkdb --version
after_script: make test-coveralls
before_install:
  # Travis uses an ancient GCC
  - export CC="gcc-4.9" CXX="g++-4.9"
  # node 0.8 comes with a non-functional version of npm
  - "if [[ $(node --version) == v0.8.* ]]; then npm install -g npm@2.1.18; fi"
