# Run tests in Docker `docker-compose up` on Node.js v4
# - install node deps first `docker-compose run agenda npm install`
agenda:
  image: nodesource/jessie:4
  command: npm test
  volumes:
    - ./:/usr/src/app
  environment:
    - RETHINKDB_HOST=rethinkdb
  links:
    - rethinkdb

rethinkdb:
  image: rethinkdb:latest
  ports:
    - "8080:8080"
    - "28015:28015"
